### ISSUE TITLE
code review for assignment1

### ISSUE THREAD

**Issue by sninala** [lalithasfdc/Native-JS-Training#1]
1. Organize your assignments into different folders. something like assignment1 or assignment2.
2. In PrintArray.js, you can replace your code with array.join().
3. code indentation missing in all the files. use any code beautification tools.
4. It's not a good practice having multiple return statements in a function. Please refer to this URL https://github.com/getify/Functional-Light-JS/blob/master/ch2.md#early-returns . basicop.js, rental.js having a function with multiple return statements. Fix them.
@lalithasfdc , please fix the code as per above review comments

**Comment by lalithasfdc** [comment]
Hi Siva, All the mentioned issues are fixed. Can you please check on this.

**Comment by sninala** [comment]
Nice. One more small correction in rentalCar, the statement days * 40 is repeated multiple times. assign it to a variable and reuse it.

**Comment by lalithasfdc** [comment]
Hi siva, in rental car, replaced statement days * 40 with an variable.
