### ISSUE TITLE
code review for assignment2

### ISSUE THREAD

**Issue by sninala** [lalithasfdc/Native-JS-Training#2]
1. In middle character.js, I feel the simple if else block would be more readable as shown below
var numberOfChars,
        middleIndex = Math.ceil((s.length / 2) - 1);
    if (s.length % 2 == 0) {
        numberOfChars = 2;
    } else {
        numberOfChars = 1;
    }
    return s.substr(middleIndex, numberOfChars);

**Comment by lalithasfdc** [comment]
Hi Siva, Updated my code, as per your comments
